<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/29
 * Time: 19:52
 */

namespace rabbit\db;


use rabbit\core\Context;
use rabbit\core\ContextTrait;

/**
 * Class DbContext
 * @package rabbit\illuminate\db
 */
class DbContext extends Context
{
    /**
     * @param string $key
     * @return array|null
     */
    public static function getAll(string $key = 'database'): ?array
    {
        return parent::getAll($key); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $config
     * @param string $key
     */
    public static function setAll($config = [], string $key = 'database'): void
    {
        parent::setAll($config, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     * @return |null
     */
    public static function get(string $name, string $key = 'database')
    {
        return parent::get($name, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param $value
     * @param string $key
     */
    public static function set(string $name, $value, string $key = 'database'): void
    {
        parent::set($name, $value, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     * @return bool
     */
    public static function has(string $name, string $key = 'database'): bool
    {
        return parent::has($name, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     */
    public static function delete(string $name, string $key = 'database'): void
    {
        parent::delete($name, $key); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public static function release(): void
    {
        $context = \Co::getContext();
        if (isset($context['database'])) {
            foreach ($context['database'] as $name => $connection) {
                $connection->release();
            }
            unset($context['database']);
        }
    }
}